###

POST http://localhost:3005/register/
Content-Type: application/json

{   
    "name":"rahul",
    "phone":"982989123",
    "email": "rahul@gmail.com",
    "password": "rahul"
    
}


###

POST http://localhost:3005/login/
Content-Type: application/json

{
    "name":"sudharshan",
    "password": "siddu"
}

###
GET http://localhost:3005/users/